# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

FROM node:lts-alpine
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci

# Environment
ENV NODE_ENV=production

# Default command: run TypeScript directly
CMD ["npx", "tsx", "src/server.ts"]
